# 
control_dt: 0.005

msg_type: "go"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "/home/theo/deploy/pre_train/go2/policy.pt"

#leg_joint2motor_idx: [3,4,5,0,1,2,9,10,11,6,7,8]
leg_joint2motor_idx: [3,0,9,6,4,1,10,7,5,2,11,8]
kps: [ 25., 25.,  25.,  25.,  25.,  25.,  25,  25., 25.,  25.,  25.,  25.]
kds: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
default_angles: [-0.1,  0.8, -1.5, 0.1, 0.8, -1.5, -0.1, 1, -1.5, 0.1, 1, -1.5]
#default_angles: [0.1, -0.1, 0.1, -0.1, 0.8, 0.8, 1, 1, -1.5, -1.5, -1.5, -1.5]
weak_motor: []
arm_waist_joint2motor_idx: []

arm_waist_kps: []

arm_waist_kds: []

arm_waist_target: [ ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [1.5, 0.9, 1]
num_actions: 12
num_obs: 52

max_cmd: [1, 1, 1]
















