msg_type: "go"     # "hg" or "go" for unitree robots
imu_type: "pelvis" # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"     # topic to publish command for the go2 robot 
lowstate_topic: "rt/lowstate" # topic to collect the data from the robot

policy_path: "../../pre_train/policy_rough.pt" # "/home/theo/deploy/pre_train/go2/policy.pt"

leg_joint2motor_idx: [3,0,9,6,4,1,10,7,5,2,11,8]                                # Conversion of the motors between isaaclab convention and the real go2 robot
default_angles: [-0.1,  0.8, -1.5, 0.1, 0.8, -1.5, -0.1, 1, -1.5, 0.1, 1, -1.5]

kps: [ 25., 25.,  25.,  25.,  25.,  25.,  25,  25., 25.,  25.,  25.,  25.]
kds: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

weak_motor: []
arm_waist_joint2motor_idx: []
arm_waist_kps: []
arm_waist_kds: []
arm_waist_target: [ ]

# DO NOT CHANGE THIS SECTION, DEPENDS ON THE ENVIRONMENT DURING TRAINING
control_dt: 0.005
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [1, 1, 1]
num_actions: 12
num_obs: 52
max_cmd: [1, 1, 1]
















